language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '7'
before_script:
  - npm prune
  - npm install -g grunt-cli
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
