language: node_js
cache:
  directories:
    - node_modules
notifications:
  email: true
node_js:
  - '7'
before_install:
  - npm i -g npm@^2.0.0
  - npm install -g grunt-cli
before_script:
  - npm prune
script:
  - npm run test
after_success:
  - npm run semantic-release
branches:
  except:
    - /^v\d+\.\d+\.\d+$/
